### ISSUE TITLE
clang-format-5.0 not found 

### ISSUE THREAD

**Issue by nomaddo** [nomaddo/native#3]
Currently, `clang-format-5.0` is unavailable in debian apt repository.
Due to this, building of the docker image `nomaddo/native` was failed.

@doe300 Is it okay for you to update it to `clang-format-7` ?

**Comment by doe300** [comment]
Yeah, that's fine for me. I may need to update some formatting with the next push, but that's okay

**Comment by nomaddo** [comment]
@doe300 Now I updated `Dockerfile`. The docker image will be updated soon in dockerhub .....
